### PR TITLE
You lost javascript version on your "master"-branch, after last commit.

### PR DESCRIPTION
**Pull request by username1565**
I did try to fix errors in tests, but cann't, and too many commits to run each travic-ci build, and see logs of jobs.
So I just deleted my old repositary, and now your fork this is fork from @sinonjs directly.
Then, I did try to upload all files, again.
You can restore your JavaScript code from to your `master`-branch, and fix some error.

All browser tests was been passed for `master`-branch.
But not all tests for `master`-branch with `JavaScript`-code was been passed in `travis-ci` jobs:
https://travis-ci.com/github/username1565/text-encoding/builds
click there to see the errors in full logs of the jobs.
There is the full info about that errors.

Also, I did create `gh-pages`-branch from `feature/typescript`-branch (after set this as `default` branch, instead master), and opened `GitHub Pages` for this branch, in the `Settings` of repositary.
And I see [here `TypeScript` browser-tests - is working](http://username1565.github.io/text-encoding/test/browser/), with additional `.js`-files.

You can recovery .js-code from this pull request, or cancel this.
I'll delete my repositary in future, if I'll fix all, and upload this consecutive, with comments.

### CODE REVIEW

**Comment by username1565** [comment]
Some files are different, so you can see the conflicts here, because your `master`-branch contains the `TypeScript` code, not `JavaScript`-code.
You can create new branch from your `master`-branch, and recovery `JavaScript`-code from this pull-request, or just by downloading zip, by this link: https://github.com/username1565/text-encoding/tree/master

As you can see here https://travis-ci.com/github/username1565/text-encoding/builds/166005443
`travis-ci` show fail for my `master`-branch (with `JavaScript/NodeJS`-code),
because tests not passed, but this tests is sucessfully runned, and all errors there is inside the tests.
Long `logs` of `Jobs` contains the errors of those tests, and maybe you can repair this.

One more question I have:
Is this possible to copy `/dist/umd/encoding.js` and `/dist/umd/encoding-indexes.js`, to the folder of repositary, and update this files, after each building from `TypeScript`-code???
This need to make able to run `browsers`-tests of this `compiled JavaScript`-files - here: http://username1565.github.io/text-encoding/test/browser/
Because in my case, I'm just using third tranch `gh-pages`:
https://github.com/username1565/text-encoding/tree/gh-pages
where `distJSbrowser/umd/`-folder created, and this contains a `JavaScripts` from `master`-branch,
(with `JavaScript/NodeJS`-scripts),
and in this case, this scripts https://github.com/username1565/text-encoding/tree/gh-pages/test/browser
not contains `new TextEncoding.` inside it,
because browser-tests return an error: `ReferenceError: TextEncoding is not defined`

**Comment by odahcam** [comment]
No code in this repository has been changed by this PR. I may be wrong, don't take it the wrong way, but it looks like you're a beginner with git so let me know if you wanna some help with it, it can be a little confusing at the beginning. I'm pretty sure you didn't have to delete your repository, I'm sorry you had to take that action to fix any git confusion.

Still, let me know if I can help with something, I sure will need help with fixing the ISO-8859-1 bug with that specific character. As [everything is green around here](https://travis-ci.com/github/zxing-js/text-encoding/builds/165867964) and both CI and CI are set, I'll be closing this PR so we can start from a new perspective. Thanks @username1565.

**Comment by odahcam** [comment]
Also, I wrote my answer before you post your second comment, so just to amend: 

> Long logs of Jobs contains the errors of those tests, and maybe you can repair this.

Yes, I can help with that.

> Is this possible to copy /dist/umd/encoding.js and /dist/umd/encoding-indexes.js, to the folder of repositary, and update this files, after each building from TypeScript-code???

That's not how it's designed to work, if you take a look at this repo you will see that everything runs perfectly. `dist` folder should be generated only when the library is built and never lives with the source code (which is here), that's why I don't nor will have a dist folder in here, because it will always be **generated** by the library build, run automatically before every test and releases made.

**Comment by username1565** [comment]
>I'll be closing this PR so we can start from a new perspective. Thanks @username1565.

Ok. 

>No code in this repository has been changed by this PR. I may be wrong

You can see changed-files in this `Pull Request`.
Also, you can compare yourself, the different forks and see all changes (after select the correct branches of this forks). Just push `New Pull Request`-button near your branch.

I see here: https://github.com/zxing-js/text-encoding/network
on this commit: https://github.com/zxing-js/text-encoding/commit/21ba9edef4dc41f2409b8cc0134570fb76e34320
Before you merge all changes from your `feature/typescript` to your `master`-branch,
old `master`-branch was contains `JavaScript`-code with two files
`lib/encodin-indexes.js` and `lib/encoding.js` + `browser`-tests and `nodeJS`-tests of this scripts.
And after you merge all changes from from your `feature/typescript` to your `master`-branch,
your `master`-branch now, contains only `TypeScript`-code with `.ts`-files,
so I think, you just lost `NodeJS`-version.

All previous files, you can see in the differences of that your commit, or just download this from my `master`-branch.


>>Long logs of Jobs contains the errors of those tests, and maybe you can repair this.

>Yes, I can help with that.

Those errors with old `.js` tests, and as I can see, all tests from `.js`-files, which is generated from your `TypeScript`-code is passed there, by your link. But I don't have that `.js`-files, and try to test old `.js`.

I see, in your `TypeScript`-version, there is automatically generated that `.js`-files, after compilation `TypeScript`-code. Is this possible to copy this `.js`-files?
Is this possible to compile this locally, and copy then from the some-folder, like `/dist/umd/blahblah.js`?

Also, I see you create your own package: https://github.com/zxing-js/text-encoding/packages/224109
Can you explain how I can create this?
I see there is included `.js`-files, and maybe this can be included direcly from `dist/umd`-folder, in `<script src="NpmLinkURL">`, but I'm not sure.

>As [everything is green](https://travis-ci.com/github/zxing-js/text-encoding/jobs/333539853) around here and both CI and CI are set

Change `console.warn` to `console.log` there.

>but it looks like you're a beginner with git so let me know if you wanna some help with it, it can be a little confusing at the beginning. I'm pretty sure you didn't have to delete your repository, I'm sorry you had to take that action to fix any git confusion.

I'm not using `git`, just `github`-interface, and for each change need to make one commit, and run one `travis-ci`-build, to fix all errors. So many commits make many garbage here: https://github.com/username1565/text-encoding/network
and I decided to delete my repositary, and upload all files again.
I want to do this again, after all fixes the tests of `old js-files`:
https://github.com/username1565/text-encoding/tree/master/lib

**Comment by odahcam** [comment]
> And after you merge all changes from from your feature/typescript to your master-branch,
your master-branch now, contains only TypeScript-code with .ts-files,
so I think, you just lost NodeJS-version.

Oh now I got it, but don't worry, I did intend to delete those files and Node will now run with JavaScript built by TypeScript's compiler.

> I'm not using git, just github-interface

I see, git is a powerful tool, it can help you in many ways.

> Change console.warn to console.log there.

I think I'll just leave it there for now, just to keep the behaviour close to the original lib.

> Can you explain how I can create this?

Yes, first you need a `package.json` file, then you can publish everything you put in a folder alongside with it by running `npm publish`. The GitHub package is basically the same, you just need to point the NPM CLI tool to GitHub's package registry with `npm config set registry https://npm.pkg.github.com/`.

> Is this possible to compile this locally, and copy then from the some-folder, like /dist/umd/blahblah.js?

Yep, you just need to run the compiler. In this forks case, I set up an NPM script, so you can build the project using NPM and node modules by running the command `npm run build` in the project's root directory.

I'm happy to see you made progress.

**Comment by username1565** [comment]
This is not a my progress. Hehheh.
I just wanted to restore all `JavaScripts`-tests, after you remove `JS`-files and tests from your `master`-branch,
and restore the `nodeJS`-version and `Node.JS`-tests of this `.js`,
and without `TypeScript`-code,
to include this `.js` directly in `<script src="http://github.com/blahblah">`.
Because not each user know how to work with `typescript` and how to compile `.js` from this,
and they just download `.js`-files and include this directly.

But I have some confuse with this tests,
and too many commits you can see and too many builds.
I'll delete all that garbage and all my branches tomorrow, and upload this again, more clearly,
but you still can see this all, if you interested it.
Some branches have sucessfull build: https://travis-ci.com/github/username1565/text-encoding/branches
So, after this all, just, will be better to just add two another tests (node and browser)
and one more `lib`-folder with that original two `JS-files`
in the TypeScript repositary + fixed `iso-8859-1`, like [I already made here](https://github.com/username1565/text-encoding/tree/fork2_typescript-with-js/test)
That's all what I wanted to do with this, by renaming that folders and edit configs -
to get successfully build for that scripts in `travis-ci`. Huahuuah.

>I think I'll just leave it there for now, just to keep the behaviour close to the original lib.

Ok,
Also, can you remove there `new TextEncoding.TextBlahblah` from TypeScript and compiled JS??
Just leave "new TextBlahblah()", without `TextEncoding.`
Because browser-tests sometimes show `ReferenceError: TextEncoding is not defined`.

Also, you can show the `label` [in that messages with `console.warn`](https://travis-ci.com/github/zxing-js/text-encoding/jobs/333539853),
[there is many another encodings](https://travis-ci.com/github/username1565/text-encoding/jobs/334456164), and I don't know what this means.

Maybe because TextEncoder, return `utf-8`-bytes only, by default,
and do not accept all another encodings, to return this bytes.
If you want, you can add supporting of this encodings in your `TypeScript`-code,
to encode and decode the different encodings,
with perspective to add many another encoding there, up to all possible encodings in the world.

**Comment by odahcam** [comment]
> to include this .js directly in <script src="http://github.com/blahblah">.
Because not each user know how to work with typescript and how to compile .js from this,
and they just download .js-files and include this directly.

That's interesting, did you know you can use **this package** on JS? The dist of this **is JS**, there's no TypeScript published. Just an example:

```html
<script src="https://unpkg.com/browse/@zxing/text-encoding@0.8.0/umd/encoding.min.js"></script>
<script>
var decoder = new TextDecoder();
// ...
</script>
```

Here, take a look on the published code (it's the generated dist folder): https://unpkg.com/browse/@zxing/text-encoding@0.8.0/

> Also, can you remove there new TextEncoding.TextBlahblah from TypeScript and compiled JS??

Oh I forgot to remove that from tests, I don't even know if it's working without it, haha.

> Also, you can show the label in that messages with console.warn,

Currently all labels are ignored, but it's interesting to add there.

**Comment by username1565** [comment]
>https://unpkg.com/browse/@zxing/text-encoding@0.8.0/umd/encoding.min.js

>Here, take a look on the published code (it's the generated dist folder): https://unpkg.com/browse/@zxing/text-encoding@0.8.0/

Wow, I see. But need to remove `/browse` from this link.
https://unpkg.com/@zxing/text-encoding@0.8.0/umd/encoding.min.js
This is correct.

And this code is correct:
```html
<script src="https://unpkg.com/@zxing/text-encoding@0.8.0/umd/encoding-indexes.js"></script>
<script src="https://unpkg.com/@zxing/text-encoding@0.8.0/umd/encoding.js"></script>
<script>
var default_browser_decoder = new TextDecoder();
console.log('Default broswser\'s TextDecoder:\n', default_browser_decoder);
/*
Default broswser's TextDecoder:
 
TextDecoder {encoding: "utf-8", fatal: false, ignoreBOM: false}
encoding: "utf-8"
fatal: false
ignoreBOM: false
__proto__: TextDecoder
*/

var included_text_decoder = new TextEncoding.TextDecoder();
console.log('Included text-decoder:\n', included_text_decoder);
/*
Included text-decoder:
 
TextDecoder {_encoding: {…}, _decoder: null, _ignoreBOM: false, _BOMseen: false, _error_mode: "replacement", …}
encoding: (...)
fatal: (...)
ignoreBOM: (...)
_BOMseen: false
_decoder: null
_do_not_flush: false
_encoding: {labels: Array(3), name: "UTF-8"}
_error_mode: "replacement"
_ignoreBOM: false
__proto__: Object
*/
</script>
```

>>Also, can you remove there new TextEncoding.TextBlahblah from TypeScript and compiled JS??

>Oh I forgot to remove that from tests, I don't even know if it's working without it, haha.

No, no. Will be better to leave this.
[When `new TextEncoding.` contains in included `.js`-files](https://unpkg.com/browse/@zxing/text-encoding@0.8.0/umd/encoding.js) (Line 4), which was been compiled from `TypeScript`,
then, as you can see from previous code,
new included `TextEncoder` and `TextDecoder` can be runned from included scripts,
without override the browser's `TextEncoder/TextDecoder`.
But you can remove this, and override default encoder/decoder, then.

>Yes, first you need a package.json file, then you can publish everything you put in a folder alongside with it by running npm publish. The GitHub package is basically the same, you just need to point the NPM CLI tool to GitHub's package registry with npm config set registry https://npm.pkg.github.com/.

Ok, thanks. Done [by this algorithm](https://github.com/username1565/text-encoding/commit/f60981910de1067609fd09ed61e032831daa33f2#commitcomment-39213588), and result - [you can see here](https://github.com/username1565/text-encoding/actions/runs/106170767), and I see `pack-artifact.zip`, with `.js`-files there.

[Here, at this line of `npmpublish.yml`](https://github.com/username1565/text-encoding/blob/f60981910de1067609fd09ed61e032831daa33f2/.github/workflows/npmpublish.yml#L71), needed to login with `NPM_TOKEN`, at first.
I see new package, but I cann't see this in https://unpkg.com, like this
https://unpkg.com/browse/@zxing/text-encoding@0.8.0/

https://unpkg.com/browse/@username1565/text-encoding@0.8.2/ -> nothing.
So, how to publish this `.js` from `pack-artifact.zip` to `unpkg`, to include this by links?

**Comment by username1565** [comment]
I just try to run workflow to publish my own package, but there is some error with autorization:
https://github.com/username1565/text-encoding/runs/679738935?check_suite_focus=true
How to fix this?

**Comment by odahcam** [comment]
> Wow, I see. But need to remove /browse from this link.

Oh sorry, I was copying the link so you could browse and probably pasted it in place of the raw file, haha.

> So, how to publish this .js from pack-artifact.zip to unpkg, to include this by links?

I think you trying too hard to copy this, the projects besides from the same fork, are now two completely different things. You don't need a build, don't need to upload artefacts nor download it. You need a much simpler config. I'm running out of battery and really can't explain right now, sorry.

**Pull request closed without merging**
