### PR TITLE
See changes in the differences.

### PR DESCRIPTION
**Pull request by username1565**
See changes [in the differences](https://github.com/zxing-js/text-encoding/pull/6/files).

### CODE REVIEW

**Comment by werthdavid** [comment]
"unauthorized branch created due to a bug that existed from May 28, 2020 to June 16, 2020"

**Comment by odahcam** [comment]
Don't worry @werthdavid , I already deleted the branch, I think this PR is still valid so we can see how to solve ISO-8859 vs. Latin1 issues. Although I would't merge this as the sources are too different and it may cause build and CI/CD pipeline issues.

**Comment by username1565** [comment]
The branch `test_resolve_conflicts` was been created to resolve conflicts between your fork, and mine,
because I did change `zxing-js` to `username1565`, and also, [there is some another differences](https://github.com/username1565/text-encoding/compare/master...username1565:test_resolve_conflicts).
So when I did try to resolve this conflicts, new branch was been created in your fork and in my fork,
and the commits to resolve conflicts go to this branch, not to my `master`-branch.

>I think this PR is still valid

No, this PR is closed from your side, after you delete that branch `test_resolve_conflicts`.

But anyway, this branch was been contains your parameters, and this Pull Request was been created,
to give you the ability to [merge this differences](https://github.com/zxing-js/text-encoding/pull/6/files)
into your `master`-branch. You can see this differences, in the details, and add this yourself, if you want.
Also, you can see this differences by [compare across forks](https://github.com/zxing-js/text-encoding/compare/master...username1565:test_resolve_conflicts).

**Comment by odahcam** [comment]
We know that branch was created automatically on our side due to a GitHub security issue. So don't worry.

> No, this PR is closed from your side

This is not relevant. The contents of the PR still here for us to analyze and learn something, thus stills valid content, just not for merging. Thanks for the PR anyway.

**Review by odahcam — COMMENTED** [review]
I'm a little concernd about this section: https://github.com/zxing-js/text-encoding/pull/6/files?file-filters%5B%5D=.js&file-filters%5B%5D=.ts#diff-f763ee408f7349c7224858b96db5caecR305-R318

As you changed the encoding labels and added a new encoding (which I believe is pretty much correct) won't it cause a breaking change in the library? I mean, people using the library, for example, to de/encode `Latin1` characters won't notice a different behavior? 

Also, in fact, started this branch with that changes and it caused me lots of test errors forcing me to rollback these changes in order to accomplish my goal here; I really want to apply these changes now, but as I had so many errors I believe we may have a backwards compatibility issue. Do you agree with that?

**Comment by username1565** [comment]
@odahcam, there, the synonyms for `latin-1` using for `iso-8859-1`,
and this encoding, like `windows-1252`, is `ascii-compatible`,
because first 128 chars in `cp1252`, and `latin-1`, this is an `ASCII`-symbols.

Just I added `ascii`-synonyms for `latin-1`, because this encoding is oldest, than `windows-1252`,
and, maybe, faster (and maybe need to make some speedtest of this).

Anyway, there is no any problems with backward compatibility, and `ascii`-chars,
can be encoded and decoded as the chars of both encoding - `windows-1252`, and as `latin-1`.

UPD:
`"iso-ir-100"`, `ibm819`, and `cp819` - need to move to `iso-8859-1`, as synonyms, too.

UPD2: [Add `latin-1` aliases](https://github.com/username1565/text-encoding/blob/e4eae2d8d4853d02972334228e015d70df5f40aa/src/encoding/encodings.ts#L293-L329), which [are registered in IANA](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), including `cp28591` and `windows-28591`.

**Comment by username1565** [comment]
```javascript
      { label: 'cp819', encoding: 'iso-8859-1' 	}, //this is IANA registered IBM alias for latin-1 encoding
```
[travis-ci builds are successful](https://travis-ci.com/github/username1565/text-encoding/builds/173381496), after fix `misc`-tests.
I do not see any problems with backward compatibility,
but if anyone still using aliases `cp819`, or `iso-ir-100`, or `ibm819` - for `windows-1252` (?!!),
then need to just change this alias [to `cp1252`, or some another](https://github.com/username1565/text-encoding/blob/8e0ebc92a3cb0bd8a037180d147202810d72474d/src/encoding/encodings.ts#L296).

**Pull request closed without merging**
